{{- if .Values.hpa.enabled }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: {{ include "telemetry.hpaName" . }}
  namespace: {{ .Release.Namespace }}

spec:
  scaleTargetRef:
    apiVersion: {{ .Values.hpa.scaleTargetRef.apiVersion }}
    kind: {{ .Values.hpa.scaleTargetRef.kind }}
    name: {{ include "telemetry.deploymentName" . }}

  minReplicas: {{ .Values.hpa.minReplicas }}

  maxReplicas: {{ .Values.hpa.maxReplicas }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}

{{- end }}