apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.secretName" . }}
  namespace: {{ .Release.Namespace }}

type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.email | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.password | quote }}

  