apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgadmin.serviceName" . }}
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: {{ .Values.pgadmin.labels.app }}

  ports:
    - port: {{ .Values.pgadmin.service.port }}
      targetPort: {{ .Values.pgadmin.service.targetPort }}

  type: {{ .Values.pgadmin.service.type }}