{{/*
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "postgres.pvcName" . }}

spec:
  storageClassName: {{ include "postgres.storageClassName" . }}

  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}

  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}

*/}}