# Deployment
replicaCount: 1

labels:
  app: simulation
  
image:
  repository: amitkkc01/axion-simulator
  tag: "5e4a9e3"
  
  pullPolicy: IfNotPresent

container:
  name: simulation-container


# api:
#   url: "http://dev.ingest.theakkc.space/api/v1/telemetry/ingest"