apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  namespace: {{ .Release.Namespace }}

type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.database.postgresDb | quote }}
