namespace: axion-dev

database:
  postgresUser: jarvis
  postgresPassword: jarvis12345
  postgresDbName: jarvis-db
  port: 5432

deployment:
  replicas: 1
  labels:
    app: telemetry

container:
  name: telemetry-container
  port: 8000

image:
  repository: amitkkc01/telemetry-arm64
  tag: "5.0.1"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"


service:
 
  selector:
    app: telemetry

  port: 80
  targetPort: 8000

  type: ClusterIP


hpa:
  enabled: true

  minReplicas: 1
  maxReplicas: 5

  targetCPUUtilizationPercentage: 70

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telemetry-deploy



ingress:
  enabled: true

  ingressClassName: azure-application-gateway

  annotations:
    appgw.ingress.kubernetes.io/health-probe-path: "/dashboard/summary"

  host: telemetry.theakkc.space

  path: "/"
  pathType: Prefix



# telemetry:
#   databaseUrl: "postgresql://jarvis:jarvis12345@dev-axion-postgres-svc:5432/jarvis-db"

environment: ""