pgadmin:
  email: jarvis@gmail.com
  password: jarvis12345
  replicas: 1

  labels:
    app: pgadmin

  container:
    name: pgadmin

  image: dpage/pgadmin4:9.17
  containerPort: 80

  config:
    enhancedCookieProtection: "False"

  service:
    name: pgadmin-dev-svc
    port: 80
    targetPort: 80
    type: ClusterIP


ingress:
  enabled: true

  name: axion-agic-ingress

  ingressClassName: azure-application-gateway

  annotations:
   # kubernetes.io/ingress.class: "azure/application-gateway"
    appgw.ingress.kubernetes.io/health-probe-path: "/misc/ping"
    appgw.ingress.kubernetes.io/ssl-redirect: "false"

  hosts:
    - host: dev.pgadmin.theakkc.shop
      paths:
        - path: /
          pathType: Prefix
          service:
            name: pgadmin-dev-svc
            port: 80
