apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "simulator.deploymentName" . }}
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}

  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}

    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: API_URL
              value: "{{ include "simulator.ingestionApiUrl" . }}"