# Deployment
replicaCount: 1

labels:
  app: simulation
  
image:
  repository: amitkkc01/simulator-arm64
  tag: "5.0.1"
  
  pullPolicy: IfNotPresent

container:
  name: simulation-container

environment: ""