apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: axion-application-set
  namespace: argocd

spec:
  generators:
    - matrix:
        generators:
          # Environment generator
          - list:
              elements:
                - env: dev
                  namespace: axion-dev

                - env: qa
                  namespace: axion-qa

                - env: prod
                  namespace: axion-prod

          # Microservice generator
          - list:
              elements:
                - app: ui
                  chartPath: axion-gitops/charts/ui-chart

                - app: telemetry
                  chartPath: axion-gitops/charts/telemetry-chart

                - app: simulator
                  chartPath: axion-gitops/charts/simulator-chart

                - app: ingestion
                  chartPath: axion-gitops/charts/ingestion-chart

                - app: postgres-db
                  chartPath: axion-gitops/charts/postgres-db-chart
                
                - app: pgadmin
                  chartPath: axion-gitops/charts/pgadmin-chart


  template:
    metadata:
      name: '{{app}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/akkc01/gitops-with-argocd.git
        targetRevision: main
        path: '{{chartPath}}'

        helm:
          valueFiles:
            - values.yaml

          values: |
            environment: '{{env}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true